name: 'Deploy - Prod'

on:
  workflow_dispatch:
  push:
    branches:
      - 'debug-*'

defaults:
  run:
    shell: bash

env:
  STAGE: 'prod'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    # if workflow_dispatch or branch name starts with debug- and commit message contains [deploy]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/debug-') && contains(github.event.head_commit.message, '[deploy]'))
    name: deploy
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
        pnvm-version: [latest]
    runs-on: ${{ matrix.os }}
    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPORT: ${{ secrets.PGPORT }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
      OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
      LLAMANODES_API_KEY: ${{ secrets.LLAMANODES_API_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup pnpm [${{ matrix.pnvm-version }}]'
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnvm-version }}

      - name: 'Setup Node.js [${{ matrix.node-version }}]'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 'Install Dependencies'
        run: |
          pnpm install --frozen-lockfile
          pnpm add --global serverless serverless-esbuild

      - name: 'Build'
        run: pnpm build
        env:
          NODE_ENV: 'production'

      - name: 'Deploy'
        run: |
          #
          # auth
          #
          serverless config credentials \
            --provider aws \
            --key ${{ env.AWS_ACCESS_KEY_ID }} \
            --secret ${{ env.AWS_SECRET_ACCESS_KEY }}
          #
          # deploy
          #
          serverless deploy \
            --config serverless.yml \
            --stage prod \
            --region ${{ env.AWS_REGION }} \
            --verbose
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # enables verbose logging
          ACTIONS_STEP_DEBUG: true
