name: 'Update Swagger & Publish'

# Grab up to date swagger JSON from AWS API Gateway
# Update Swagger UI static S3 bucket website with new JSON

on:
  workflow_dispatch:
  schedule:
    # run every day at 12:00 UTC
    - cron: '0 12 * * *'

defaults:
  run:
    shell: bash

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOYER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Bun 🍞'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Pull Latest Swagger'
        env:
          AWS_GATEWAY_API_ID_DEV: ${{ secrets.AWS_GATEWAY_API_ID_DEV }}
        run: |
          bun add --global tsx@latest
          bun ./scripts/update-swagger.ts || tsx ./scripts/update-swagger.ts

      - name: 'curl Swagger UI index.html'
        working-directory: './docs/swagger'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_SWAGGER_URL }}
          INDEX_HTML_URL: 'https://gist.githubusercontent.com/o-az/36b94d57a8df23421f229a15b5ae7a10/raw/d684172357888c68ac0d9a5007e82bdc5f812e90/index.html'
        run: |
          curl --silent --location $INDEX_HTML_URL --output index.html

      - name: 'Update Swagger Bucket'
        working-directory: './docs/swagger'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_SWAGGER }}
        run: |
          rm -rf .gitkeep || true
          aws s3 sync ./ s3://$AWS_S3_BUCKET
