name: 'Test API Endpoints'

# Runs:
# - daily at 00:00 UTC
# - on manual trigger through GitHub Actions UI
# - on push to any branch
on:
  schedule:
    # cron syntax: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  endpoints-cron-test:
    name: 'Test API Endpoints'
    runs-on: [ubuntu-latest]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Lint, Format & Typecheck'
        run: |
          pnpm lint
          pnpm format
          pnpm typecheck

      - name: 'Test'
        run: pnpm test
